
CREATE TABLE KHOA (
    MaKhoa CHAR(5) PRIMARY KEY,
    TenKhoa VARCHAR(100),
    TruongKhoa VARCHAR(100)
);

CREATE TABLE LOP (
    MaLop CHAR(10) PRIMARY KEY,
    TenLop VARCHAR(100),
    MaKhoa CHAR(5),
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
);

CREATE TABLE SINHVIEN (
    MaSV CHAR(5) PRIMARY KEY,
    HoTen VARCHAR(100),
    MaLop CHAR(10),
    NamSinh INT,
    FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
);

CREATE TABLE MONHOC (
    MaMH CHAR(5) PRIMARY KEY,
    TenMH VARCHAR(100),
    SoTinChi INT
);

CREATE TABLE KETQUA (
    MaSV CHAR(5),
    MaMH CHAR(5),
    Diem DECIMAL(4,2),
    PRIMARY KEY(MaSV, MaMH),
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV),
    FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
);